# basic test runner for sourmash plugin:
# 1. install stuff in environment.yaml from conda (with caching)
# 2. install this package
# 3. run tests with 'make test'

name: "run tests"
on:
  pull_request:
  push:
    branches: [latest]
jobs:
  mamba:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: cache conda
      uses: actions/cache@v4
      env:
        CACHE_NUMBER: 1
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

    - name: setup conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: 3.12
        channels: conda-forge,bioconda
        miniforge-variant: Mambaforge
        miniforge-version: latest
        use-mamba: true
        mamba-version: "*"
        activate-environment: sourmash_dev
        auto-activate-base: false

    - run: conda info
    - run: conda list
    - run: conda config --show

    - name: install dependencies
      shell: bash -l {0}
      run: mamba env update -n sourmash_dev -f environment.yml

    - name: install package
      shell: bash -l {0}
      run: pip install .

    - name: run python tests
      shell: bash -l {0}
      run: make test

    - name: build examples
      shell: bash -l {0}
      run: make test
